### ISSUE TITLE
broken vendor package

### ISSUE THREAD

**Issue by 0xUnkn0wN** [gin-contrib/sentry#7]
Hello,

on import i got this issues:

![image](https://user-images.githubusercontent.com/33736372/36379160-d9b3deee-157d-11e8-83f0-a027a884fbdb.png)

my imports:

- "github.com/getsentry/raven-go"
- "github.com/gin-contrib/sentry"
- "github.com/gin-gonic/gin"

Detail error messages: 

> message: 'cannot use "github.com/getsentry/raven-go".DefaultClient (type *"github.com/getsentry/raven-go".Client) as type *"github.com/gin-contrib/sentry/vendor/github.com/getsentry/raven-go".Client in argument to sentry.Recovery'

> message: 'cannot use sentry.Recovery("github.com/getsentry/raven-go".DefaultClient, true) (type "github.com/gin-contrib/sentry/vendor/github.com/gin-gonic/gin".HandlerFunc) as type "github.com/gin-gonic/gin".HandlerFunc in argument to router.Use'

Maybe it is only a vendor problem

I hope this could help you to find and fix the error

Greets Jonathan

**Comment by MarkusFreitag** [comment]
Are there any updates regarding this issue?

**Comment by MarkusFreitag** [comment]
In go 1.10 it works fine again.

**Comment by JonathanHeinz** [comment]
@MarkusFreitag i still have this problem

**Comment by xoco70** [comment]
I get the same issue on go 1.11
